'use client'

import Link from 'next/link'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { useLanguage, type LangCode } from '@/lib/language-context'

type HearingData = {
  title: string
  subtitle: string
  backLink: string
  ctaBtn: string
  sections: {
    danger: { heading: string; p1: string; p2: string }
    dbScale: {
      heading: string
      intro: string
      rows: { label: string; value: string; highlight?: 'warn' | 'danger' | 'bold' }[]
      footnote: string
    }
    rule6060: {
      heading: string
      intro: string
      volume: { icon: string; title: string; desc: string }
      time: { icon: string; title: string; desc: string }
    }
    anc: { heading: string; p1: string; p2: string; p3: string }
    eq: { heading: string; p1: string; p2: string; ctaDesc: string }
  }
}

const CONTENT: Record<LangCode, HearingData> = {
  ko: {
    title: '청력 보호 가이드',
    subtitle: '오랫동안 좋은 음악을 즐기기 위한 필수 청취 습관',
    backLink: '← EQ 가이드로 돌아가기',
    ctaBtn: '볼륨을 낮춰도 선명한 나만의 EQ 찾기',
    sections: {
      danger: {
        heading: '1. 소음성 난청, 왜 위험할까?',
        p1: '세계보건기구(WHO)에 따르면 전 세계 젊은 층 약 10억 명이 안전하지 않은 청취 습관으로 인해 청력 손실 위험에 노출되어 있습니다. 이어폰이나 헤드폰을 통해 큰 소리에 장시간 노출되면 귀 내부의 유모세포(Hair Cells)가 손상됩니다.',
        p2: '가장 무서운 점은 한 번 손상된 유모세포는 현대 의학으로 재생할 수 없다는 것입니다. 소음성 난청은 서서히 진행되기 때문에 본인이 인지했을 때는 이미 늦은 경우가 많습니다.',
      },
      dbScale: {
        heading: '2. 안전한 볼륨의 기준은?',
        intro: '전문가들이 권장하는 안전한 소음 노출 기준은 85dB(데시벨) 이하입니다.',
        rows: [
          { label: '소곤거리는 소리', value: '30dB (안전)' },
          { label: '일상적인 대화', value: '60dB (안전)' },
          { label: '시끄러운 식당, 진공청소기', value: '70~80dB (주의)' },
          { label: '안전 기준선 (8시간 이상 노출 금지)', value: '85dB', highlight: 'bold' },
          { label: '지하철 소음, 잔디깎이', value: '90~100dB (위험)', highlight: 'warn' },
          { label: '클럽, 록 콘서트, 최대 볼륨 이어폰', value: '105~110dB (매우 위험)', highlight: 'danger' },
        ],
        footnote: '* 스마트폰 볼륨의 60~70% 수준이 보통 80~85dB 정도에 해당합니다.',
      },
      rule6060: {
        heading: '3. 청력을 지키는 \'60 / 60 법칙\'',
        intro: '청각 전문가들이 가장 기억하기 쉬운 규칙으로 추천하는 60/60 법칙입니다.',
        volume: {
          icon: '🔊',
          title: '볼륨은 최대 60% 이하로',
          desc: '스마트폰 등 재생 기기의 최대 볼륨의 60%를 넘기지 마세요. 볼륨 제한 또는 헤드폰 안전 기능을 활성화하는 것이 좋습니다.',
        },
        time: {
          icon: '⏱️',
          title: '하루 60분 청취 후 휴식',
          desc: '연속으로 60분 동안 음악을 들었다면, 반드시 이어폰을 빼고 귀에 10~15분 이상의 조용한 휴식 시간을 주어야 합니다.',
        },
      },
      anc: {
        heading: '4. 노이즈 캔슬링(ANC)과 청력 보호의 관계',
        p1: '액티브 노이즈 캔슬링(ANC) 기능은 주변 소음을 상쇄해 주는 기술입니다. 이 기술은 청력 보호에 매우 큰 도움이 됩니다.',
        p2: '지하철이나 버스 같은 시끄러운 환경(보통 80~90dB)에서는 주변 소음을 뚫고 음악을 듣기 위해 무의식적으로 볼륨을 높이게 됩니다.',
        p3: '노이즈 캔슬링 기능이 있는 이어폰을 사용하면, 낮은 볼륨으로도 음악을 선명하게 감상할 수 있어 청력 보호에 매우 효과적입니다.',
      },
      eq: {
        heading: '5. EQ 튜닝을 통한 청력 보호 효과',
        p1: '맞지 않는 이어폰으로 음악을 들을 때, 특정 대역(예: 보컬)이 잘 들리지 않으면 전체 볼륨을 올리게 됩니다. 이렇게 되면 이미 충분히 큰 다른 대역의 소리까지 과도하게 커져 귀에 무리를 줍니다.',
        p2: 'EQ FreeSet을 통해 이어폰의 밸런스를 평탄하게 맞추면, 전체 볼륨을 낮춰도 모든 악기와 보컬의 소리가 선명하게 들리는 효과를 얻을 수 있으며, 이는 곧 청력 보호로 이어집니다.',
        ctaDesc: '볼륨을 낮춰도 선명한 나만의 EQ 찾기',
      },
    },
  },
  en: {
    title: 'Hearing Protection Guide',
    subtitle: 'Essential listening habits for enjoying music for years to come',
    backLink: '← Back to EQ Guide',
    ctaBtn: 'Find My EQ — Clear Sound at Lower Volume',
    sections: {
      danger: {
        heading: '1. Why Is Noise-Induced Hearing Loss So Dangerous?',
        p1: 'According to the WHO, around 1 billion young people worldwide are at risk of hearing loss due to unsafe listening habits. Prolonged exposure to loud sounds through earphones or headphones damages the hair cells (cilia) inside the ear.',
        p2: 'The most frightening aspect is that once damaged, hair cells cannot be regenerated by modern medicine. Noise-induced hearing loss progresses gradually — by the time you notice it, significant damage may already have occurred.',
      },
      dbScale: {
        heading: '2. What Is a Safe Volume Level?',
        intro: 'Experts recommend keeping sound exposure below 85 dB.',
        rows: [
          { label: 'Whisper', value: '30 dB (safe)' },
          { label: 'Normal conversation', value: '60 dB (safe)' },
          { label: 'Loud restaurant, vacuum cleaner', value: '70–80 dB (caution)' },
          { label: 'Safety threshold (no more than 8 hrs)', value: '85 dB', highlight: 'bold' },
          { label: 'Subway noise, lawnmower', value: '90–100 dB (dangerous)', highlight: 'warn' },
          { label: 'Club, rock concert, max volume earphones', value: '105–110 dB (very dangerous)', highlight: 'danger' },
        ],
        footnote: '* 60–70% of your smartphone\'s maximum volume typically corresponds to around 80–85 dB.',
      },
      rule6060: {
        heading: '3. The 60/60 Rule for Hearing Protection',
        intro: 'The 60/60 rule is the simplest guideline recommended by hearing specialists.',
        volume: {
          icon: '🔊',
          title: 'Keep volume at or below 60%',
          desc: 'Do not exceed 60% of your device\'s maximum volume. Activating a volume limiter or headphone safety feature is highly recommended.',
        },
        time: {
          icon: '⏱️',
          title: 'Take a break after 60 minutes',
          desc: 'After 60 continuous minutes of listening, remove your earphones and give your ears at least 10–15 minutes of quiet rest.',
        },
      },
      anc: {
        heading: '4. How Active Noise Cancellation (ANC) Protects Your Hearing',
        p1: 'Active Noise Cancellation (ANC) uses opposite sound waves to neutralize ambient noise. This technology significantly aids hearing protection.',
        p2: 'In noisy environments like subways or buses (typically 80–90 dB), you unconsciously raise the volume to hear your music over the background noise.',
        p3: 'Using earphones with ANC or good passive isolation (in-ear, foam tips) allows you to hear music clearly at lower volumes — a major benefit for your hearing health.',
      },
      eq: {
        heading: '5. How EQ Tuning Protects Your Hearing',
        p1: 'When certain frequencies (e.g., vocals) are hard to hear through an unbalanced earphone, you turn up the volume — pushing already-loud frequencies even higher, stressing your ears.',
        p2: 'Flattening your earphone\'s response with EQ FreeSet means all frequencies come through at the right level. You can turn the volume down while still hearing every instrument and vocal clearly — directly protecting your hearing.',
        ctaDesc: 'Find your personalized EQ for clear sound at lower volume',
      },
    },
  },
  zh: {
    title: '听力保护指南',
    subtitle: '长期享受优质音乐的必备聆听习惯',
    backLink: '← 返回EQ指南',
    ctaBtn: '寻找低音量也清晰的专属EQ',
    sections: {
      danger: {
        heading: '1. 噪音性耳鸣为何如此危险？',
        p1: '据世界卫生组织(WHO)数据，全球约10亿年轻人因不安全的聆听习惯而面临听力损失风险。长时间通过耳机接触高分贝声音会损伤耳内的毛细胞。',
        p2: '最可怕的是，一旦损伤的毛细胞在现代医学中无法再生。噪音性耳鸣是渐进性的，很多人意识到时已经太晚了。',
      },
      dbScale: {
        heading: '2. 安全音量标准是什么？',
        intro: '专家建议的安全噪音暴露标准是85分贝以下。',
        rows: [
          { label: '耳语声', value: '30dB（安全）' },
          { label: '日常对话', value: '60dB（安全）' },
          { label: '嘈杂餐厅、吸尘器', value: '70~80dB（注意）' },
          { label: '安全基准线（禁止超过8小时暴露）', value: '85dB', highlight: 'bold' },
          { label: '地铁噪音、割草机', value: '90~100dB（危险）', highlight: 'warn' },
          { label: '夜店、摇滚演唱会、最大音量耳机', value: '105~110dB（极其危险）', highlight: 'danger' },
        ],
        footnote: '* 智能手机音量的60~70%左右通常对应80~85dB。',
      },
      rule6060: {
        heading: '3. 保护听力的"60/60法则"',
        intro: '60/60法则是听力专家推荐的最易记住的规则。',
        volume: {
          icon: '🔊',
          title: '音量不超过最大值的60%',
          desc: '不要超过播放设备最大音量的60%。建议启用音量限制或耳机安全功能，确保不超过85分贝。',
        },
        time: {
          icon: '⏱️',
          title: '聆听60分钟后休息',
          desc: '连续聆听60分钟后，必须摘下耳机，给耳朵至少10~15分钟的安静休息时间。',
        },
      },
      anc: {
        heading: '4. 主动降噪(ANC)与听力保护的关系',
        p1: '主动降噪(ANC)技术通过抵消周围噪音来保护听力，对听力保护非常有帮助。',
        p2: '在地铁或公交等嘈杂环境（通常80~90dB）中，为了听清音乐，人们会无意识地调高音量。',
        p3: '使用具有降噪功能或高隔音性能（入耳式、泡沫耳套）的耳机，可以在较低音量下清晰聆听音乐，对听力保护非常有效。',
      },
      eq: {
        heading: '5. EQ调音的听力保护效果',
        p1: '使用不匹配的耳机听音乐时，某些频段（如人声）听不清就会调高整体音量，导致其他已经足够大的频段进一步放大，对耳朵造成负担。',
        p2: '通过EQ FreeSet将耳机频响调平后，即使降低整体音量，所有乐器和人声也能清晰聆听，直接起到保护听力的效果。',
        ctaDesc: '寻找低音量也清晰的专属EQ',
      },
    },
  },
  ja: {
    title: '聴力保護ガイド',
    subtitle: '長く音楽を楽しむための必須の聴取習慣',
    backLink: '← EQガイドに戻る',
    ctaBtn: '音量を下げても鮮明な自分だけのEQを探す',
    sections: {
      danger: {
        heading: '1. 騒音性難聴はなぜ危険なのか？',
        p1: 'WHO（世界保健機関）によると、世界で約10億人の若者が安全でない聴取習慣により聴力損失のリスクにさらされています。イヤホンやヘッドホンで大きな音に長時間さらされると、耳内部の有毛細胞（Hair Cells）が損傷します。',
        p2: '最も恐ろしいのは、一度損傷した有毛細胞は現代医学では再生できないという点です。騒音性難聴は徐々に進行するため、気づいた時にはすでに手遅れの場合が多いです。',
      },
      dbScale: {
        heading: '2. 安全な音量の基準は？',
        intro: '専門家が推奨する安全な騒音暴露基準は85dB（デシベル）以下です。',
        rows: [
          { label: 'ひそひそ声', value: '30dB（安全）' },
          { label: '日常会話', value: '60dB（安全）' },
          { label: 'うるさいレストラン、掃除機', value: '70~80dB（注意）' },
          { label: '安全基準線（8時間以上の暴露禁止）', value: '85dB', highlight: 'bold' },
          { label: '地下鉄の騒音、芝刈り機', value: '90~100dB（危険）', highlight: 'warn' },
          { label: 'クラブ、ロックコンサート、最大音量イヤホン', value: '105~110dB（非常に危険）', highlight: 'danger' },
        ],
        footnote: '* スマートフォンのボリュームの60~70%程度が通常80~85dBに相当します。',
      },
      rule6060: {
        heading: '3. 聴力を守る「60/60ルール」',
        intro: '聴覚専門家が最も覚えやすいルールとして推薦する60/60ルールです。',
        volume: {
          icon: '🔊',
          title: '音量は最大60%以下に',
          desc: 'スマートフォンなど再生機器の最大音量の60%を超えないようにしてください。音量制限やヘッドホンの安全機能を有効にすることをお勧めします。',
        },
        time: {
          icon: '⏱️',
          title: '60分の聴取後は休憩を',
          desc: '連続で60分間音楽を聴いたら、必ずイヤホンを外して耳に10~15分以上の静かな休憩を与えましょう。',
        },
      },
      anc: {
        heading: '4. ノイズキャンセリング（ANC）と聴力保護の関係',
        p1: 'アクティブノイズキャンセリング（ANC）機能は周囲の騒音を打ち消す技術です。この技術は聴力保護に非常に大きな助けになります。',
        p2: '地下鉄やバスのような騒がしい環境（通常80~90dB）では、周囲の騒音を超えて音楽を聴くために無意識に音量を上げてしまいます。',
        p3: 'ノイズキャンセリング機能を持つイヤホンを使用すると、低い音量でも音楽を鮮明に楽しめるため、聴力保護に非常に効果的です。',
      },
      eq: {
        heading: '5. EQチューニングによる聴力保護効果',
        p1: '合わないイヤホンで音楽を聴くとき、特定の帯域（例：ボーカル）が聴き取りにくくなり全体の音量を上げてしまいます。これにより、すでに十分大きい他の帯域の音もさらに大きくなり耳に負担をかけます。',
        p2: 'EQ FreeSetでイヤホンのバランスを整えると、全体の音量を下げても全ての楽器とボーカルが鮮明に聴こえる効果が得られ、これが直接的な聴力保護につながります。',
        ctaDesc: '音量を下げても鮮明な自分だけのEQを探す',
      },
    },
  },
}

export default function HearingHealthContent() {
  const { lang } = useLanguage()
  const c = CONTENT[lang] ?? CONTENT.ko
  const s = c.sections

  return (
    <main className="container mx-auto px-4 py-8 max-w-3xl">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">{c.title}</h1>
        <p className="text-muted-foreground">{c.subtitle}</p>
      </div>

      <div className="space-y-10">
        {/* Why dangerous */}
        <section>
          <h2 className="text-2xl font-bold mb-4 pb-2 border-b">{s.danger.heading}</h2>
          <div className="space-y-4 text-muted-foreground leading-relaxed">
            <p>{s.danger.p1}</p>
            <p>{s.danger.p2}</p>
          </div>
        </section>

        {/* dB scale */}
        <section>
          <h2 className="text-2xl font-bold mb-4 pb-2 border-b">{s.dbScale.heading}</h2>
          <div className="space-y-4 text-muted-foreground leading-relaxed">
            <p>{s.dbScale.intro}</p>
            <Card>
              <CardContent className="p-6">
                <ul className="space-y-3">
                  {s.dbScale.rows.map((row, i) => (
                    <li
                      key={i}
                      className={`flex justify-between items-center border-b pb-2 last:border-0 last:pb-0 ${
                        row.highlight === 'danger' ? 'text-red-500 font-bold' :
                        row.highlight === 'warn' ? 'text-orange-500' :
                        row.highlight === 'bold' ? 'font-bold text-foreground' : ''
                      }`}
                    >
                      <span>{row.label}</span>
                      <span>{row.value}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
            <p className="text-sm mt-2">{s.dbScale.footnote}</p>
          </div>
        </section>

        {/* 60/60 rule */}
        <section>
          <h2 className="text-2xl font-bold mb-4 pb-2 border-b">{s.rule6060.heading}</h2>
          <div className="space-y-4 text-muted-foreground leading-relaxed">
            <p>{s.rule6060.intro}</p>
            <div className="grid md:grid-cols-2 gap-4">
              {[s.rule6060.volume, s.rule6060.time].map((card) => (
                <Card key={card.title} className="bg-primary/5 border-primary/20">
                  <CardHeader>
                    <CardTitle className="text-xl">{card.icon} {card.title}</CardTitle>
                  </CardHeader>
                  <CardContent className="text-sm">{card.desc}</CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* ANC */}
        <section>
          <h2 className="text-2xl font-bold mb-4 pb-2 border-b">{s.anc.heading}</h2>
          <div className="space-y-4 text-muted-foreground leading-relaxed">
            <p>{s.anc.p1}</p>
            <p>{s.anc.p2}</p>
            <p>{s.anc.p3}</p>
          </div>
        </section>

        {/* EQ benefit */}
        <section>
          <h2 className="text-2xl font-bold mb-4 pb-2 border-b">{s.eq.heading}</h2>
          <div className="space-y-4 text-muted-foreground leading-relaxed">
            <p>{s.eq.p1}</p>
            <p>{s.eq.p2}</p>
            <div className="text-center mt-6">
              <Button asChild className="btn-premium">
                <Link href="/test">{c.ctaBtn}</Link>
              </Button>
            </div>
          </div>
        </section>

        <div className="flex justify-between items-center pt-8 border-t">
          <Button variant="ghost" asChild>
            <Link href="/info">{c.backLink}</Link>
          </Button>
        </div>
      </div>
    </main>
  )
}
